basic WebUSB suport
OpenGammaProject/Gamma-MCA pull request #29
Opened 2023-02-08 21:41 UTC by slimonslimon

WebUSB api will be used as fallback API when WebSerial api is not available. It uses bundled javascript WebUSB FTDI Driver v0.01a from: https://github.com/pmp-p/webusb-ftdi/blob/master/webusb-ftdi.js

Write support with WebUSB is now disabled - need test.
Write support with WebSerial is not tested. I need secondary usb-to-serial, to check if it works.

2023-02-08 21:41 UTC, slimonslimon commented
FIY @kaklik

2023-02-09 11:26 UTC, Phoenix1747 commented
Please create the pull request for the `dev` branch not `main`. Thanks!

2023-02-09 13:57 UTC, Phoenix1747 commented
Did some changes to the code over at your fork: https://github.com/UniversalScientificTechnologies/Gamma-MCA/pull/2/

Please merge and I'll have a look at it once again. Then I'll probably merge as well. The Web Serial stuff all still works, so if the Web USB works on your end, great job!

2023-02-09 13:59 UTC, Phoenix1747 requested changes
Waiting for https://github.com/UniversalScientificTechnologies/Gamma-MCA/pull/2/ merge.

2023-02-10 13:01 UTC, Phoenix1747 commented on source/serial.ts
> +      this.port.close();
Please add an await here, just to be sure. I forgot that.

2023-02-10 13:01 UTC, Phoenix1747 commented on source/serial.ts
> +      this.port.close();
Please add an await here too, just to be sure.

2023-02-10 14:02 UTC, slimonslimon commented
Fix WebSerial Write means Fix WebUSB Write... sorry

2023-02-10 14:27 UTC, slimonslimon commented
I tested folowing setups using two USBToSerial devices:

PC terminal <-> PC OpenMCA (WebSerial)
PC terminal <-> PC OpenMCA (WebUSB - using modified main.ts - disable WebSerial)
PC terminal <-> Android OpenMCA (WebUSB)
PC OpenMCA (WebSerial) <-> Android OpenMCA(WebUSB)

2023-02-10 14:30 UTC, Phoenix1747 commented
And did everything work?

2023-02-10 15:05 UTC, slimonslimon commented
In my opinion yes.

But there are two things to discuse:
  - Send function consumes string, read functiuon produce Uint8Array - it's okey? 
  - Send function add '\n'. as End of Line, but parser of incoming data expected '\r\n' as End of Line

2023-02-10 16:00 UTC, Phoenix1747 commented
> Send function consumes string, read functiuon produce Uint8Array - it's okey?

Think that's fine. The only thing that's important is that both WebSerial and WebUSBSerial return the same type. The remaining conversion to strings is the same for both, so the SerialManager can handle that.

> Send function add '\n'. as End of Line, but parser of incoming data expected '\r\n' as End of Line

I think it would actually be better to remove the `\r` from the EOL. It just needs to use `\n` actually. I'll need to have a look at the serial data reduction to catch cases where either `\r\n` and `\n` are received. I'll do that once this PR is finished. (Some whitespace trimming fun)

2023-02-10 20:27 UTC, slimonslimon reviewed
shut i press this? (PR was accepted before)

2023-02-10 20:34 UTC, slimonslimon commented
I still see changes requesed, but i think that I accept all all changes by your PR...

2023-02-10 20:46 UTC, Phoenix1747 approved these changes

2023-02-10 20:47 UTC, Phoenix1747 commented
Yeah, don't worry. Nice job.

2023-02-10 20:47 UTC, merged

2023-02-11 14:09 UTC, Phoenix1747 commented
@slimonslimon Can you please give the current `dev` branch another try with some WebUSB clients? I actually don't have any FTDI serial devices here, so can't test it unfortunately.

Had to fix some problems when multiple devices were connected and/or disconnected at the same time while recording. I haven't touched the WebUSBSerial class much, but just to be sure that the checks in `main.ts` didn't break something.

When this is working I will push the current `dev` branch to main, create a version tag and the new feature will be public.

2023-02-11 19:59 UTC, slimonslimon commented
Im sorry but, current dev doesnt work properly with WebUSBSerial. 

First think i found: comment this line: 
https://github.com/OpenGammaProject/Gamma-MCA/blob/dev/source/serial.ts#L34
cause that it makes infinite loop without "await", so javascript cannot do any other "task" than this. (As far as I understand javascript) (when device not sending data - our device sends data about 1time per 10 seconds)

But i stil doesnt work when i remove comment, and I dont see other problem directly.

2023-02-11 20:09 UTC, Phoenix1747 commented
> cause that it makes infinite loop without "await", so javascript cannot do any other "task" than this. (As far as I understand javascript) (when device not sending data - our device sends data about 1time per 10 seconds)

Okay I see. That's something different with WebSerial then. Because WebSerial works without any delays. I will uncomment your delay in WebUSBSerial.

Is it more of a problem with finding and selecting the right port, or is there an issue with the recording on your end?

2023-02-11 20:14 UTC, slimonslimon commented
The issue was between keyboard and chair.... 

When I want use (for dev purpose) the WebUSB on PC (where chromium has debug menus), I should remove kernel module whose block the usb device... I forget this...

2023-02-11 20:29 UTC, Phoenix1747 commented
Ok cool, thanks for testing! Will bump it to `main` then (with the uncommented line from above).

2023-02-11 20:34 UTC, slimonslimon commented
Well... I tested it with two devices and PC with blocked WEBSerial API (one is USB2Serial which dont have opposite connection now, and second is LabDOS which produces data). When I have open GammaMCA-console with LABDOS and remove USB2Serial from USB, console keep recieving data. 

GammaMCA.console works on Android. 

So I thing you can publis it, because Im not able to setup more complicated experiment now. I will test it deeper on next week, if it is needed.

2023-02-11 20:37 UTC, Phoenix1747 commented
Yeah, all the WebSerial things still work just fine. So if at least _something_ works for now (even rudimentary) with WebUSB, then it's a clear win. We can check more complicated scenarios in the future anyways.

2023-02-16 22:36 UTC, Phoenix1747 commented
Just tested it with a random, new USB UART converter and made some minor adjustments to the filter so that it accepts _any_ FTDI chip, not only one productId. Works great now, tested with an Arduino Uno as a dummy, even the console shows fine.